language: node_js
node_js:
  - '0.8'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-deanhtml5' ]; then cd .. && eval "mv $currentfolder generator-deanhtml5" && cd generator-deanhtml5; fi

